### ISSUE TITLE
Lobe UI FOUC (flash of unstyled content)

### ISSUE THREAD

**Issue by Zain-ul-din** [lobehub/lobe-ui#103]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

It seems like [ui.lobehub.com](https://ui.lobehub.com/) is using react server components that's why the actual theme changes after some time which causes the screen to flash white for a second before showing the dark theme. 

### 🚦 期望结果 | Expected Behavior

Please can you guide how can we prevent FOUC (flash of unstyled content) when using react server components in Next Js 13 App directory?

### 📷 复现步骤 | Recurrence Steps

https://github.com/lobehub/lobe-ui/assets/78583049/ac9ac1d8-647b-4b2f-a382-dbe6715e88ff

**Comment by SivertGullbergHansen** [comment]
Bump

**Comment by arvinxx** [comment]
@sivert-io @Zain-ul-din just check lobechat implement here: https://github.com/lobehub/lobe-chat/pull/220/commits/4002d601f3e5b442ce2c7ace03b92902ebe1715a#diff-0bccc9e6e125cd0067adf17a2297ef439b7ef8df6170ccc762db0b8cdd845fbf
