### ISSUE TITLE
[Request] ChatItem/EditableMessage里的markdown增加图表展示

### ISSUE THREAD

**Issue by GUOYUHAN** [lobehub/lobe-ui#131]
### 🥰 需求描述 | Feature Description

希望可以在markdown中添加图表展示

### 🧐 解决方案 | Proposed Solution

增加类似echarts/chart.js的数据兼容，或者提供扩展

**Comment by arvinxx** [comment]
可以自行扩展，参考 https://ui.lobehub.com/components/markdown#custom-plugins
