### ISSUE TITLE
[Request] this is no description of List, ListItemProps which were used in lobe chat

### ISSUE THREAD

**Issue by 1huangx** [lobehub/lobe-ui#132]
### 🥰 需求描述 | Feature Description

I found lobe chat used List, ListItemProps to render session list, I'm a little confused about how to use them and cannot find descriotion in lobe UI docs, do you have plan to add them to docs?

### 🧐 解决方案 | Proposed Solution

add docs of List, ListItemProps

### 📝 补充信息 | Additional Information

Thanks very much

**Comment by felixiho** [comment]
hi @arvinxx I'd like to work on updating the docs to include List component
