### ISSUE TITLE
[Question] 太喜欢这些icon了，不知道哪里才可以下载到这完整的包

### ISSUE THREAD

**Issue by onlinedear** [lobehub/lobe-ui#154]
### 🧐 问题描述 | Proposed Solution

![下载](https://github.com/lobehub/lobe-ui/assets/10751712/97299092-6eab-49ae-88de-a6d16fadfcd1)

**Comment by sonnyding1** [comment]
如果你是在说emoji的话，可以用这个repo的FluentEmoji：https://ui.lobehub.com/components/fluent-emoji

其他资源可以看一下https://github.com/lobehub/lobe-assets
