### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by shzzzzz** [lobehub/lobe-ui#169]
### 🧐 问题描述 | Proposed Solution

import { Markdown } from '@lobehub/ui';
import React from 'react';

const str = "当前内存占用率为$82.51\\%$。";

const Comp: React.FC= () => {
    return (
        <Markdown
           allowHtml
           enableLatex
           fullFeaturedCodeBlock
           >
             {str}
        </Markdown>
    );
};

LaTeX 的解析是不是还有一点问题？

### 📝 补充信息 | Additional Information

dependencies:
@lobehub/ui 1.144.5

**Comment by arvinxx** [comment]
最新的看应该是没问题了？
<img width="861" alt="image" src="https://github.com/user-attachments/assets/d35c30d5-cfc8-454f-9131-bc717c0783b5">
