### ISSUE TITLE
[Bug] 组件库文档打包失败

### ISSUE THREAD

**Issue by git-Renpingjun** [lobehub/lobe-ui#189]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

执行命令`npm run docs:build`文档打包时失败，控制台信息如下：
```
> dumi build

info  - dumi v2.2.17
info  - Umi v4.3.11

load typescript lib fail! Error: 加载失败: (0)[https://unpkg.com/lib/lib.esnext.d.ts [".d.ts",".ts",".tsx","/index.d.ts","/index.ts","/index.tsx","",".js",".jsx","/index.js","/index.jsx"]]
```
![image](https://github.com/user-attachments/assets/c8c86169-1a73-439e-b067-c7e039f62fae)

### 🚦 期望结果 | Expected Behavior

打包成功

### 📷 复现步骤 | Recurrence Steps

本地跑起来后执行打包命令：npm run docs:build

**Comment by canisminor1990** [comment]
尝试用 pnpm 安装依赖
