### ISSUE TITLE
[Question] mdx下有14个组件，文档里只有一个

### ISSUE THREAD

**Issue by git-Renpingjun** [lobehub/lobe-ui#197]
### 🧐 问题描述 | Proposed Solution

如图示，mdx下有14个组件，文档里只展示了一个，怎么给全部放开
![image](https://github.com/user-attachments/assets/022094f6-3a6a-46e8-b7a2-cebbc8c770e4)
![image](https://github.com/user-attachments/assets/f90718c6-7b66-462b-89c9-a8c879685ed8)

**Comment by canisminor1990** [comment]
fixed
