### ISSUE TITLE
[Request] Can you provide a release version of Vue? Please

### ISSUE THREAD

**Issue by okGentlemen** [lobehub/lobe-ui#219]
### 🥰 需求描述 | Feature Description

Your project is fantastic, it's simply perfect! However, we are currently facing a challenge and would like to use it in the Vue project. We hope to receive a release version of Vue and look forward to it.

### 🧐 解决方案 | Proposed Solution

We need a Vue distribution

**Comment by felixiho** [comment]
@okGentlemen I don't think this is a simplistic request as this library is entirely written in react js. 
In other to release a vue version, we'll have to re-write library using Vue from scratch. 
I'm not sure this is part of the projects roadmap. 
However, you could create a library in Vue and try to recreate as much components as possible from here.

**Comment by arvinxx** [comment]
we won't plan to have a vue version. Sorry.
