### ISSUE TITLE
[Request] 代码块支持默认折叠

### ISSUE THREAD

**Issue by zhuba-Ahhh** [lobehub/lobe-ui#235]
### 🥰 需求描述 | Feature Description

https://github.com/lobehub/lobe-ui/blob/1b89e526ca86e308ac94b068bde0480d659ff717/src/Highlighter/FullFeatured.tsx#L35

### 🧐 解决方案 | Proposed Solution

支持传入配置是否默认折叠

### 📝 补充信息 | Additional Information

[FullFeatured](https://github.com/lobehub/lobe-ui/blob/1b89e526ca86e308ac94b068bde0480d659ff717/src/Highlighter/FullFeatured.tsx#L35)

**Comment by zhuba-Ahhh** [comment]
我顺手加一下吧，有需求用到比较急

**Comment by canisminor1990** [comment]
Ok 加一个 defaultExpand 吧
