### ISSUE TITLE
[Request] Use Non-Chinese CDN

### ISSUE THREAD

**Issue by jangrewe** [lobehub/lobe-ui#39]
### 🥰 需求描述 | Feature Description

Chinese Great Firewall seems to be blocking my (static, unchangeable) IPs.

### 🧐 解决方案 | Proposed Solution

Upload the assets that are fetched from CDN to a different CDN, like jsDelivr or CDNjs.

### 📝 补充信息 | Additional Information

```
$ curl -v https://npm.elemecdn.com
*   Trying 180.163.40.36:443...
* connect to 180.163.40.36 port 443 failed: Connection timed out
*   Trying 180.163.40.38:443...
* After 84400ms connect time, move on!
* connect to 180.163.40.38 port 443 failed: Connection timed out
*   Trying 180.163.40.41:443...
* After 42200ms connect time, move on!
* connect to 180.163.40.41 port 443 failed: Connection timed out
*   Trying 180.163.40.35:443...
* After 21099ms connect time, move on!
* connect to 180.163.40.35 port 443 failed: Connection timed out
*   Trying 180.163.40.37:443...
* After 10549ms connect time, move on!
* connect to 180.163.40.37 port 443 failed: Connection timed out
*   Trying 180.163.40.34:443...
* After 5275ms connect time, move on!
* connect to 180.163.40.34 port 443 failed: Connection timed out
*   Trying 180.163.40.19:443...
* After 2636ms connect time, move on!
* connect to 180.163.40.19 port 443 failed: Connection timed out
* Failed to connect to npm.elemecdn.com port 443: Connection timed out
* Closing connection 0
curl: (28) Failed to connect to npm.elemecdn.com port 443: Connection timed out
```

**Comment by Wxh16144** [comment]
Is that the resource cited here https://github.com/lobehub/lobe-ui/blob/b1f0327b7e68a44a12917f133b2847702e971387/.dumirc.ts#L63

**Comment by Wxh16144** [comment]
Maybe you can modify this tool method to switch cdn? https://github.com/lobehub/lobe-ui/blob/b1f0327b7e68a44a12917f133b2847702e971387/src/utils/genCdnUrl.ts#L12-L15

**Comment by Wxh16144** [comment]
It felt like it couldn't take care of everyone and had to manually change some of the code

**Comment by nikolay167** [comment]
Hi hi! 

Meanwhile we are the global cdn provider which can help with acceleration of static and dynamic.

Also we have option for mainland China cdn delivery by providing cdn domain with enabled mainland china acceleration.

Do you want to try our solution to compare the quality ?

**Comment by jangrewe** [comment]
@Wxh16144 If using a different CDN is not an option for you, could you then maybe include these files locally with the theme?

**Comment by canisminor1990** [comment]
## ConfigProvider

The `proxy` provides two CDN resolution addresses, `aliyun` and `unpkg`, with `aliyun` as the default. This can be configured through the `cdn` attribute of `ConfigProvider`.


At the same time, it provides custom CDN configuration, set `proxy` to `custom` and configure through the `customCdnFn` attribute.

```ts
import { ConfigProvider, Logo } from '@lobehub/ui';

export default () => {
  return (
    <ConfigProvider config={{
        proxy: 'custom',
        customCdnFn: (e: {pkg:string, version:string, path:string}) => `https://yourcdn/${pkg}/${version}/${path}`
    }}>
      <Logo />
    </ConfigProvider>
  );
};
```
