### ISSUE TITLE
[Bug] Homepage's button has some trouble in a specific action.

### ISSUE THREAD

**Issue by catynaimiao** [lobehub/lobe-ui#44]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

at the Lobe UI homepage.

https://ui.lobehub.com/ 

At the webpage of intro about the Fast section icon.
when pointer over the Icon of the fast icon , the below editor's icons can't reacted.

Maybe this effect would occur in other same scenes.

### 🚦 期望结果 | Expected Behavior

the defualt pointer with the editor buttons when after the hover Fast Icon.

### 📷 复现步骤 | Recurrence Steps

<img width="963" alt="bug" src="https://github.com/lobehub/lobe-ui/assets/60805902/b1c97e09-82cf-49ad-85cf-26384f63dbf2">

**Comment by canisminor1990** [comment]
fixed
