### ISSUE TITLE
[Bug] Module not found: Error: Can't resolve '@splinetool/runtime' 

### ISSUE THREAD

**Issue by ONLY-yours** [lobehub/lobe-ui#79]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

error - ./node_modules/@splinetool/react-spline/dist/react-spline.js:2:0-56
Module not found: Error: Can't resolve '@splinetool/runtime'

**Comment by canisminor1990** [comment]
用什么包管理装的依赖？

**Comment by ONLY-yours** [comment]
> @ONLY-yours 用什么包管理装的依赖？

yarn

**Comment by ONLY-yours** [comment]
我看他们一直都是 peerDependencies 声明但是 dependencies 没有加，应该会出错才对？maybe

**Comment by canisminor1990** [comment]
这是次级依赖吧

**Comment by ONLY-yours** [comment]
> 这是次级依赖吧



> 这是次级依赖吧，你是不是用的tnpm

不是啊，我在家里呢，用不了 tnpm 哈哈哈
![image](https://github.com/lobehub/lobe-ui/assets/52664827/f597c50c-bec0-40e6-9827-39aa3279af84)

**Comment by canisminor1990** [comment]
奇怪了 lobe chat 直接引用了没报错

**Comment by ONLY-yours** [comment]
感觉会报错来着哈哈，但是奇怪都没报错哈哈哈
难道是我环境有问题？

**Comment by canisminor1990** [comment]
你pr补一个？

**Comment by canisminor1990** [comment]
peer 父级没有 会自己装吧？

**Comment by ONLY-yours** [comment]
> peer 父级没有 会自己装吧？

应该不会的，peer声明的上级依赖要自己安装

**Comment by canisminor1990** [comment]
他deps里也写了啊

**Comment by canisminor1990** [comment]
第一个就是

**Comment by ONLY-yours** [comment]
> 第一个就是

那是 dev 的呀
不是 dependencies 呀
![image](https://github.com/lobehub/lobe-ui/assets/52664827/df8441e1-80e5-4a6d-aa4c-d3c1787197d6)

**Comment by canisminor1990** [comment]
哦 看错了

**Comment by ONLY-yours** [comment]
> 你加么 还是我加

我来 稍等一会
