### ISSUE TITLE
[Bug] 在输入带换行的长文本时chatitem返回内容不换行

### ISSUE THREAD

**Issue by w840980261** [lobehub/lobe-ui#81]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

输入文案
<img width="824" alt="image" src="https://github.com/lobehub/lobe-ui/assets/31058539/759dd6ae-a811-47c6-8410-6c08a28eb8c9">
在该平台的展示效果
<img width="384" alt="image" src="https://github.com/lobehub/lobe-ui/assets/31058539/045e2bc1-e31d-4888-9a66-49a934a92a2f">
因为css中缺少了white-space: pre-wrap;

### 📝 补充信息 | Additional Information

通过排查，应该添加在 [lobe-ui](https://github.com/lobehub/lobe-ui/tree/master)/[src](https://github.com/lobehub/lobe-ui/tree/master/src)/[ChatItem](https://github.com/lobehub/lobe-ui/tree/master/src/ChatItem)
/style.ts 中

**Comment by canisminor1990** [comment]
我思考下 ，目前默认走的是 md 的解析方式，语法上是双换行符才回换行，同时把多个换行都格式化为 2 个

**Comment by w840980261** [comment]
经过你的提醒，我发现gpt返回时的内容也因为这个解析方式换行显示异常。
预期效果
<img width="999" alt="image" src="https://github.com/lobehub/lobe-ui/assets/31058539/4d6d2b62-660c-4219-83eb-7a7a2ecbd8c8">
实际效果
<img width="753" alt="image" src="https://github.com/lobehub/lobe-ui/assets/31058539/aa22b119-8d59-4263-a8f6-24ca0901aad2">

**Comment by arvinxx** [comment]
> 我思考下 ，目前默认走的是 md 的解析方式，语法上是双换行符才会真实换行，同时把多个换行都格式化为 2 个

我感觉还是得支持单换行，小红书这个场景用户也不用 markdown 的，就是正常换行。

**Comment by canisminor1990** [comment]
Fixed: https://github.com/lobehub/lobe-ui/commit/c5b4f6b3881cad257d476dd3ac8bef26c1cad3c7
