### ISSUE TITLE
[Bug] CheckBox 在深色模式显示异常

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-ui#84]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

看不太清，浅色模式正常

### 📷 复现步骤 | Recurrence Steps

<img width="585" alt="image" src="https://github.com/lobehub/lobe-ui/assets/29084441/4c6e9a09-c101-42c2-ba52-86b1c5cc193a">

**Comment by canisminor1990** [comment]
fix in https://github.com/lobehub/lobe-ui/commit/a1e81af8daea3b486c1f0e2d0400df59ecf34b53
