### ISSUE TITLE
[Bug] firefox context menu position issue

### ISSUE THREAD

**Issue by m1911star** [lobehub/lobe-ui#91]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Firefox

<img width="730" alt="图片" src="https://github.com/lobehub/lobe-ui/assets/4948120/3190c75a-5862-4a8c-85c0-426c30732605">

### 🐛 问题描述 | Bug Description

<img width="1860" alt="图片" src="https://github.com/lobehub/lobe-ui/assets/4948120/70a83f05-4cdb-4b09-897b-e84f111dc47f">

https://ui.lobehub.com/components/context-menu

**Comment by Wxh16144** [comment]
This question should be obsolete。
<img width="1792" alt="image" src="https://github.com/lobehub/lobe-ui/assets/32004925/46787d07-6843-4fb7-a340-bca96022fa09">

**Comment by m1911star** [comment]
OK
